version: '3.8'
services:
  web:
    image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-django-app:latest
    container_name: django_web
    command: bash -c "python manage.py migrate && gunicorn --bind :8000 --workers 3 myproject.wsgi:application"
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:17.3-alpine
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data: