# Generated by Django 5.1.5 on 2025-01-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='myapp.major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', related_query_name='student', to='myapp.major'),
            preserve_default=False,
        ),
    ]
