# Generated by Django 5.1.5 on 2025-01-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_professor_department_alter_schedule_class_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='major',
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', related_query_name='course', to='myapp.major'),
            preserve_default=False,
        ),
    ]
