# Generated by Django 5.1.5 on 2025-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_section_major_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(help_text='Provide the number of credits the course is worth'),
        ),
        migrations.AlterField(
            model_name='section',
            name='building',
            field=models.CharField(help_text='Provide the name of the building', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='room',
            field=models.CharField(help_text='Provide the room number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], help_text='Select which semester the section will take place', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.IntegerField(help_text='Provide the year the section will take place'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_enrolled',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], help_text='Select the semester the student will begin classes', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_enrolled',
            field=models.IntegerField(help_text='Provide the year the student will begin classes'),
        ),
    ]
