# Generated by Django 5.1.5 on 2025-01-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_section_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='sections', related_query_name='section', to='myapp.student'),
        ),
    ]
