# Generated by Django 5.1.5 on 2025-02-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_section_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionEnrollment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.section',),
        ),
    ]
