# Generated by Django 5.1.5 on 2025-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_enrollment_section_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(choices=[('Humanities', 'Humanities'), ('Communication & Media Studies', 'Communication & Media Studies'), ('Law', 'Law'), ('Social Sciences', 'Social Sciences'), ('Business & Management', 'Business & Management'), ('Education', 'Education'), ('Health & Medical Sciences', 'Health & Medical Sciences'), ('Biological & Life Sciences', 'Biological & Life Sciences'), ('Physical Sciences', 'Physical Sciences'), ('Mathematics & Statistics', 'Mathematics & Statistics'), ('Computer Science & Information Technology', 'Computer Science & Information Technology'), ('Engineering', 'Engineering')], max_length=50),
        ),
    ]
